# Should Handbook use a custom join message?
UseCustomJoinMessage: false

# If you set the value above to true, then what should the custom join message be?
CustomJoinMessage: '&7[&6Join&7] &a%name%'

# Should we send the motd.yml to a player on join?
SendMotdOnJoin: true
