#########################################################
#    _    _                 _ _                 _       # 
#   | |  | |               | | |               | |      # 
#   | |__| | __ _ _ __   __| | |__   ___   ___ | | __   #
#   |  __  |/ _` | '_ \ / _` | '_ \ / _ \ / _ \| |/ /   #
#   | |  | | (_| | | | | (_| | |_) | (_) | (_) |   <    #
#   |_|  |_|\__,_|_| |_|\__,_|_.__/ \___/ \___/|_|\_\   #
#########################################################

# Excuse me for that cheesy ASCII Art, but I felt like it was necessary
# for me to include something weird into this configuration file.

# Here are the variables you can use in Strings:
# Remember that %world% will only work in the MOTD, custom join message etc. etc. or whenever there is a single player involved
#
#   +------------------+-----------------------------------------------------------+
#   |     Variable     |                          Output                           |
#   +------------------+-----------------------------------------------------------+
#   | %name%           | Player name                                               |
#   | %online%         | Amount of players online                                  |
#   | %onlineList%     | List of players online                                    |
#   | %time%           | The time of the default (overworld) world                 |
#   | %time_worldname% | Current time in the specified world                       |
#   | %world%          | World of the current player (only works in certain areas) |
#   +------------------+-----------------------------------------------------------+
 
# Should Handbook use a custom join message?
UseCustomJoinMessage: false

# If you set the value above to true, then what should the custom join message be?
CustomJoinMessage: '&7[&6Join&7] &a%name% &9in &a%world%'

# Should we send the motd.yml to a player on join?
SendMotdOnJoin: true
