name: Handbook
version: 0.6.2
description: An essential plugin for any server!
author: bernhardkiv
authors: [bernhardkiv, ZeRoyalCoder]
website: http://www.github.com/bernhardkiv
main: com.newgarbo.handbook.main.Handbook

commands:
 vanish:
  description: Disappear into absolute nothingness!
  aliases: [v, va]
 playerinfo:
  description: Get information about a player
  aliases: [pi, pinfo, info]
 broadcast:
  description: Broadcast a message to the server
  aliases: [bc, bc, hbbroadcast]
 flight:
  description: Toggle flight for yourself or other people!
  aliases: [fly, flying, hbfly]
 heal:
  description: Heal yourself or others
  aliases: [hbheal]
 feed:
  description: Feed yourself!
  aliases: [hbfeed]
